# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'The OSCAR Book Companion: Code Examples and Errata'
description:      'OSCAR, an Open Source Computer Algebra Research System written in Julia'
url:              https://oscar.github.io
baseurl:          /oscar-website

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# for SEO plugin
tagline:          'The OSCAR Book Companion'
logo:             /public/OSCAR_logo.png

exclude:
  - _config_production.yml
  - etc
  - LICENSE.hyde.md
  - README.hyde.md
  - README.md
